#ifndef __HTTP_H__
#define __HTTP_H__

/* ================== 主页：选择 4G 或 Wi-Fi ================== */

const char *index_html =
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "  <meta charset='UTF-8'>"
    "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "  <title>设备配网</title>"
    "  <style>"
    "    body { font-family: Arial, sans-serif; text-align: center; padding: 30px; background: #f5f5f5; }"
    "    h1 { color: #333; margin-bottom: 40px; }"
    "    .btn {"
    "      display: block; width: 80%; padding: 15px; margin: 15px auto;"
    "      font-size: 18px; border: none; border-radius: 8px; cursor: pointer;"
    "    }"
    "    .btn-4g { background: #ff6b6b; color: white; }"
    "    .btn-wifi { background: #4ecdc4; color: white; }"
    "  </style>"
    "</head>"
    "<body>"
    "  <h1>请选择联网方式</h1>"
    "  <button class='btn btn-4g' onclick=\"window.location.href='/g4_setup'\">使用 4G 上网</button>"
    "  <button class='btn btn-wifi' onclick=\"window.location.href='/wifi_setup'\">使用 Wi-Fi 联网</button>"
    "</body>"
    "</html>";


/* ================== 4G 配网页面（占位） ================== */
const char *g4_setup_html =
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "  <meta charset='UTF-8'>"
    "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "  <title>4G 配网</title>"
    "  <style>"
    "    body { font-family: Arial, sans-serif; text-align: center; padding: 40px; background: #f0f0f0; }"
    "    h2 { color: #d32f2f; }"
    "    .note { background: #fff8e1; padding: 20px; border-radius: 8px; margin: 20px 0; }"
    "    .btn-back {"
    "      display: inline-block; margin-top: 20px; padding: 10px 20px;"
    "      background: #90caf9; color: #0d47a1; text-decoration: none; border-radius: 5px;"
    "    }"
    "  </style>"
    "</head>"
    "<body>"
    "  <h2>4G 联网配置</h2>"
    "  <div class='note'>"
    "    <p>当前版本暂未集成 4G 模块功能。</p>"
    "  </div>"
    "  <a href='/' class='btn-back'>返回首页</a>"
    "</body>"
    "</html>";



/* ================== Wi-Fi 配网页（JS 内联，最可靠） ================== */
static const char *wifi_setup_html =
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "  <meta charset='UTF-8'>"
    "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "  <title>Wi-Fi 配网</title>"
    "  <style>"
    "    body { font-family: Arial, sans-serif; padding: 20px; background: #fff; }"
    "    h2 { text-align: center; color: #333; }"
    "    .btn { padding: 10px 20px; margin: 10px 5px; font-size: 16px; cursor: pointer; }"
    "    .scan-btn { background: #4ecdc4; color: white; border: none; border-radius: 5px; }"
    "    .connect-btn { background: #51cf66; color: white; border: none; border-radius: 5px; }"
    "    input { width: 90%; padding: 10px; margin: 10px 0; border: 1px solid #ccc; border-radius: 4px; }"
    "    .ap-list { margin-top: 20px; }"
    "    .ap-item { padding: 12px; margin: 8px 0; background: #f9f9f9; border-left: 4px solid #4ecdc4; cursor: pointer; }"
    "    .ap-item:hover { background: #e0f7fa; }"
    "    .rssi { float: right; color: #888; font-size: 14px; }"
    "    #status { margin-top: 10px; padding: 10px; font-size: 14px; color: #555; }"
    "  </style>"
    "</head>"
    "<body>"
    "  <h2>Wi-Fi 配网</h2>"
    /* 关键修改：去掉 onclick 属性，只用 id 来绑定事件 */
    "  <button class='btn scan-btn' id='scanBtn' type='button'>扫描附近 Wi-Fi</button>"
    "  <div id='status'></div>"
    "  <div id='apList' class='ap-list'></div>"
    ""
    "  <form id='wifiForm'>"
    "    <input type='text' id='ssid' name='ssid' placeholder='Wi-Fi 名称 (SSID)' required><br>"
    "    <input type='password' id='password' name='password' placeholder='Wi-Fi 密码' required><br>"
    "    <button type='submit' class='btn connect-btn'>连接 Wi-Fi</button>"
    "  </form>"
    ""
    /* 关键修改：JS 直接内联，不依赖外部脚本加载 */
    "  <script>"
    "    var scanBtn = document.getElementById('scanBtn');"
    "    var apList = document.getElementById('apList');"
    "    var statusDiv = document.getElementById('status');"
    "    var wifiForm = document.getElementById('wifiForm');"
    ""
    "    function setStatus(msg) {"
    "      statusDiv.innerText = msg;"
    "    }"
    ""
    "    function scanWiFi() {"
    "      setStatus('正在扫描，请稍候...');"
    "      apList.innerHTML = '';"
    "      var xhr = new XMLHttpRequest();"
    "      xhr.open('GET', '/scan', true);"
    "      xhr.timeout = 15000;"  /* 扫描可能需要几秒，设15秒超时 */
    "      xhr.onload = function() {"
    "        if (xhr.status !== 200) {"
    "          setStatus('扫描失败: HTTP ' + xhr.status);"
    "          return;"
    "        }"
    "        var aps;"
    "        try { aps = JSON.parse(xhr.responseText); } catch(e) {"
    "          setStatus('JSON 解析错误');"
    "          return;"
    "        }"
    "        if (aps.length === 0) {"
    "          setStatus('未发现可用 Wi-Fi');"
    "          return;"
    "        }"
    "        setStatus('发现 ' + aps.length + ' 个网络:');"
    "        var html = '';"
    "        for (var i = 0; i < aps.length; i++) {"
    "          var ap = aps[i];"
    "          if (!ap.ssid || ap.ssid.trim() === '') continue;"
    "          var rssi = ap.rssi;"
    "          var bars = '弱';"
    "          if (rssi > -60) bars = '强';"
    "          else if (rssi > -75) bars = '中';"
    "          html += '<div class=\"ap-item\" data-ssid=\"' + ap.ssid + '\">' +"
    "                  ap.ssid + ' <span class=\"rssi\">' + bars + ' (' + rssi + ' dBm)</span>' +"
    "                  '</div>';"
    "        }"
    "        apList.innerHTML = html;"
    /* 给每个 AP 项绑定点击事件 */
    "        var items = apList.querySelectorAll('.ap-item');"
    "        for (var j = 0; j < items.length; j++) {"
    "          items[j].addEventListener('click', function() {"
    "            var s = this.getAttribute('data-ssid');"
    "            document.getElementById('ssid').value = s;"
    "            document.getElementById('password').focus();"
    "            setStatus('已选择: ' + s);"
    "          });"
    "        }"
    "      };"
    "      xhr.onerror = function() {"
    "        setStatus('网络错误，请检查是否连接到 ESP32-AP');"
    "      };"
    "      xhr.ontimeout = function() {"
    "        setStatus('扫描超时，请重试');"
    "      };"
    "      xhr.send();"
    "    }"
    ""
    "    function connectWiFi(e) {"
    "      e.preventDefault();"
    "      var ssid = document.getElementById('ssid').value.trim();"
    "      var pass = document.getElementById('password').value;"
    "      if (!ssid) { setStatus('请输入 SSID'); return; }"
    "      setStatus('正在连接 ' + ssid + ' ...');"
    "      var body = 'ssid=' + encodeURIComponent(ssid) + '&password=' + encodeURIComponent(pass);"
    "      var xhr = new XMLHttpRequest();"
    "      xhr.open('POST', '/connect', true);"
    "      xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');"
    "      xhr.onload = function() {"
    "        if (xhr.status !== 200) {"
    "          setStatus('请求失败: HTTP ' + xhr.status);"
    "          return;"
    "        }"
    "        var data;"
    "        try { data = JSON.parse(xhr.responseText); } catch(e2) {"
    "          setStatus('响应解析失败');"
    "          return;"
    "        }"
    "        if (data && data.ok) {"
    "          setStatus('已发起连接，正在等待...');"
    "          pollStatus();"
    "        } else {"
    "          setStatus(data && data.message ? data.message : '连接失败');"
    "        }"
    "      };"
    "      xhr.onerror = function() { setStatus('网络错误'); };"
    "      xhr.send(body);"
    "    }"
    ""
    "    function pollStatus() {"
    "      var count = 0;"
    "      var timer = setInterval(function() {"
    "        count++;"
    "        if (count > 20) { clearInterval(timer); setStatus('连接超时'); return; }"
    "        var xhr = new XMLHttpRequest();"
    "        xhr.open('GET', '/status', true);"
    "        xhr.timeout = 3000;"
    "        xhr.onload = function() {"
    "          if (xhr.status !== 200) return;"
    "          var s;"
    "          try { s = JSON.parse(xhr.responseText); } catch(e3) { return; }"
    "          if (s && s.connected) {"
    "            clearInterval(timer);"
    "            setStatus('连接成功! IP: ' + (s.ip || ''));"
    "          }"
    "        };"
    "        xhr.onerror = function() {};"
    "        xhr.send();"
    "      }, 1500);"
    "    }"
    ""
    /* 绑定事件 */
    "    scanBtn.addEventListener('click', scanWiFi);"
    "    wifiForm.addEventListener('submit', connectWiFi);"
    "  </script>"
    "</body>"
    "</html>";

    

#endif // __HTTP_H__